### ISSUE TITLE
Issue with mesos.native not being found.

### ISSUE THREAD

**Issue by tegansnyder** [mesosphere/RENDLER#40]
I'm not sure how this happened. I followed the advance cluster course on the mesosphere website and built out a four node cluster. I then decided to try installing RENDLER on it to get a feel for how a custom framework internals work.

After cloning the repo down to my master node I tried executing the python script and was greeted with an the following import error:

```sh
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named native
```

So I went looking to see what modules python is aware of. In the packages folder: `/usr/lib/python2.7/site-packages/mesos` I just see just two module folders:
- cli  
- interface

I don't see a `native` folder. This module must have not been installed when I followed the advanced course to build out the cluster. I spent a bit of time trying to figure out the issue then settled with installing the .egg by doing the following:

```sh
# visit https://open.mesosphere.com/downloads/mesos/
# find the latest Python egg for my OS
wget http://downloads.mesosphere.io/master/centos/7/mesos-0.26.0-py2.7-linux-x86_64.egg
sudo easy_install mesos-0.26.0-py2.7-linux-x86_64.egg
```

**Comment by tegansnyder** [comment]
I'm hoping if someone else runs into this they can find this issue. Closing it now.

**Comment by jrenner** [comment]
I had the same problem and here is how I solved it:
1. follow all instructions on mesos site for how to install on POSIX
2. go into your src/python/native dir and run setup.py install
3. go into your src/python dir and run setup.py install
